import { Outfit } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/authProviders/AuthProvider";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AuthProvider>{children}</AuthProvider> <Toaster />
      </body>
    </html>
  );
}
